name: Release Build

on:
  push:
    tags:
      ["v?[0-9]+.*"]

jobs:
  get-version:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.version.outputs.result }}
    steps:
      - name: Get version from tag name
        uses: actions/github-script@v6
        id: version
        with:
          result-encoding: string
          script: |
            let version = /^v?(?<v>([0-9]+\.){2,3}[0-9]+)$/i
                .exec("${{ github.ref_name }}")?.groups?.v;
            console.log(`Version: ${version}`);
            return version;

  build:
    runs-on: windows-latest
    needs: get-version
    if: ${{ needs.get-version.outputs.version }}
    env:
      Platform: "x64"
      Version: ${{ needs.get-version.outputs.version }}
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ hashFiles('*.csproj') }}
      - name: Build Release for ${{ env.Platform }}
        run: >
          dotnet publish -c Release -r "win-${{ env.Platform }}"
          -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:Version=${{ env.Version }}
          -p:IncludeNativeLibrariesForSelfExtract=true
          --no-self-contained -o "build/"
      - name: Remove pdb
        run: Remove-Item "build/*.pdb" -Force
      - uses: actions/upload-artifact@v3
        with:
          name: BASTool_${{ env.Version }}_${{ env.Platform }}
          path: build/
      - name: Pack files
        run: 7z a BASTool_${{ env.Version }}_${{ env.Platform }}.zip build/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: BASTool_${{ env.Version }}_${{ env.Platform }}.zip
